variable "droplet_name" {}
variable "droplet_image" {}
variable "droplet_region" {}
variable "droplet_size" {}
variable "droplet_ssh_keys_fingerprints" {}
variable "firewall_name" {}
variable "domain_name" {}
variable "delimited_domain_name" {}

variable "registry_domain_name" {}
variable "portainer_domain_name" {}
variable "www_domain_name" {}
variable "ssh_client_private_key" {}
variable "primary_user_name" {}
variable "ssh_client_pub_key" {}
variable "spaces_accesskey" {}
variable "spaces_secretkey" {}
variable "spaces_region" {}
variable "spaces_bucket" {}
variable "spaces_root" {}
variable "registry_port" {}
variable "docker_user" {}
variable "docker_password" {}
variable "letsencrypt_email" {}